export const nutritionalData = {
  "protein": {
    "low": [
      { "item": "Almond Milk (240 mL)", "protein_g": 1 },
      { "item": "Apple (1 medium, ~180 g)", "protein_g": 0.5 },
      { "item": "Banana (1 medium, ~120 g)", "protein_g": 1 },
      { "item": "Beer (355 mL)", "protein_g": 1 },
      { "item": "Broccoli (100 g)", "protein_g": 3 },
      { "item": "Brown Rice (100 g cooked)", "protein_g": 3 },
      { "item": "Corn (100 g)", "protein_g": 3 },
      { "item": "Green Peas (100 g)", "protein_g": 5 },
      { "item": "Mushrooms (100 g)", "protein_g": 3 },
      { "item": "Potato (100 g)", "protein_g": 2 },
      { "item": "Quinoa (100 g cooked)", "protein_g": 4 },
      { "item": "Soda (355 mL)", "protein_g": 0 },
      { "item": "Spinach (100 g)", "protein_g": 3 },
      { "item": "Sweet Potato (100 g)", "protein_g": 1.5 },
      { "item": "White Bread (1 slice, ~30 g)", "protein_g": 2 },
      { "item": "Whole Wheat Bread (1 slice, ~30 g)", "protein_g": 3 },
      { "item": "Mineral Water (500 mL)",             "protein_g": 0 },
      { "item": "Celery (2 stalks, ~100 g)",           "protein_g": 0.7 },
      { "item": "Avocado ½ (100 g)",                   "protein_g": 2.0 },
      { "item": "Apple (1 medium, ~180 g)",            "protein_g": 0.4 }
    ],
    "medium": [
      { "item": "Almonds (28 g)", "protein_g": 6 },
      { "item": "Black Beans (100 g cooked)", "protein_g": 9 },
      { "item": "Cottage Cheese (100 g)", "protein_g": 11 },
      { "item": "Chia Seeds (28 g)", "protein_g": 5 },
      { "item": "Chickpeas (100 g cooked)", "protein_g": 8 },
      { "item": "Edamame (100 g)", "protein_g": 11 },
      { "item": "Egg (1 large, ~50 g)", "protein_g": 6 },
      { "item": "Greek Yogurt (100 g)", "protein_g": 10 },
      { "item": "Lentils (100 g cooked)", "protein_g": 9 },
      { "item": "Peanut Butter (32 g / 2 tbsp)", "protein_g": 8 },
      { "item": "Peanuts (28 g)", "protein_g": 7 },
      { "item": "Protein Bar (≈50 g)", "protein_g": 10 },
      { "item": "Soy Milk (240 mL)", "protein_g": 7 },
      { "item": "Tofu (100 g)", "protein_g": 8 },
      { "item": "Tabbouleh (200 g)", "protein_g": 5.2 },
      { "item": "Hummus + Khubz (½ cup + pita)", "protein_g": 11 },
      { "item": "Falafel (6 pcs)", "protein_g": 15.5 },
      { "item": "Grilled Hamour Fish (150 g)", "protein_g": 13 },
      { "item": "Walnuts (28 g)", "protein_g": 4 }
    ],
    "high": [
      { "item": "Beef (100 g)", "protein_g": 26 },
      { "item": "Cheddar Cheese (100 g)", "protein_g": 25 },
      { "item": "Chicken Breast (100 g)", "protein_g": 30 },
      { "item": "Lamb (100 g)", "protein_g": 25 },
      { "item": "Pork Chop (100 g)", "protein_g": 26 },
      { "item": "Salmon (100 g)", "protein_g": 25 },
      { "item": "Seitan (100 g)", "protein_g": 25 },
      { "item": "Shrimp (100 g)", "protein_g": 24 },
      { "item": "Tuna (100 g)", "protein_g": 25 },
      { "item": "Turkey Breast (100 g)", "protein_g": 29 },
      { "item": "Fattoush Salad (250 g)", "protein_g": 27 },
      { "item": "Protein Shake (30 g whey)", "protein_g": 30 },
      { "item": "Machboos Rice & Chicken (350 g)", "protein_g": 32 },
      { "item": "Whey Protein Powder (30 g scoop)", "protein_g": 24 },
      { "item": "Chicken Shawarma Wrap",               "protein_g": 48 }
    ]
  },
  "potassium": {
    "low": [
      { "item": "Apple (1 medium, ~180 g)", "potassium_mg": 195 },
      { "item": "Grapes (75 g)", "potassium_mg": 155 },
      { "item": "Strawberries (75 g)", "potassium_mg": 125 },
      { "item": "Watermelon (75 g)", "potassium_mg": 85 },
      { "item": "Cabbage (75 g cooked)", "potassium_mg": 147 },
      { "item": "Cauliflower (75 g cooked)", "potassium_mg": 88 },
      { "item": "Cucumber (75 g)", "potassium_mg": 80 },
      { "item": "Egg (1 large, ~50 g)", "potassium_mg": 63 },
      { "item": "Green beans (75 g cooked)", "potassium_mg": 90 },
      { "item": "Portabella Mushrooms (100 g cooked)", "potassium_mg": 529 },
      { "item": "Canned Peas (75 g, drained)", "potassium_mg": 148 },
      { "item": "Potato Chips (28 g)", "potassium_mg": 466 },
      { "item": "Milk (240 mL)", "potassium_mg": 366 },
      { "item": "Almonds (28 g)", "potassium_mg": 200 },
      { "item": "Cashews (28 g)", "potassium_mg": 160 },
      { "item": "Peanuts (28 g)", "potassium_mg": 180 },
      { "item": "Oatmeal (100 g cooked)", "potassium_mg": 164 },
      { "item": "White Bread (30 g slice)", "potassium_mg": 32 }
    ],
    "medium": [
      { "item": "Dried Apricots (35 g)", "potassium_mg": 378 },
      { "item": "Cantaloupe (75 g)", "potassium_mg": 215 },
      { "item": "Kiwi (1 medium, ~75 g)", "potassium_mg": 240 },
      { "item": "Mango (1 medium, ~200 g)", "potassium_mg": 325 },
      { "item": "Orange (1 medium, ~180 g)", "potassium_mg": 240 },
      { "item": "Pineapple (100 g)", "potassium_mg": 180 },
      { "item": "Tomato (1 medium, ~120 g)", "potassium_mg": 292 },
      { "item": "Beets (75 g)", "potassium_mg": 259 },
      { "item": "Bell pepper (75 g)", "potassium_mg": 314 },
      { "item": "Broccoli (75 g)", "potassium_mg": 229 },
      { "item": "Corn (100 g cooked)", "potassium_mg": 384 },
      { "item": "Spinach (75 g cooked)", "potassium_mg": 420 },
      { "item": "Butternut Squash (75 g)", "potassium_mg": 291 },
      { "item": "Sweet Potato (130 g medium baked)", "potassium_mg": 450 },
      { "item": "Tomato Juice (240 mL)", "potassium_mg": 527 },
      { "item": "White Rice (100 g cooked)", "potassium_mg": 54 },
      { "item": "Black Beans (100 g cooked)", "potassium_mg": 306 },
      { "item": "Lentils (100 g cooked)", "potassium_mg": 366 },
      { "item": "Quinoa (100 g cooked)", "potassium_mg": 318 },
      { "item": "Trail Mix (75 g)", "potassium_mg": 514 }
    ],
    "high": [
      { "item": "Avocado (1/2 medium, ~75 g)", "potassium_mg": 487 },
      { "item": "Banana (1 medium, ~120 g)", "potassium_mg": 422 },
      { "item": "Grapefruit (1 medium, ~230 g)", "potassium_mg": 415 },
      { "item": "Honeydew (175 g)", "potassium_mg": 388 },
      { "item": "Prune Juice (240 mL)", "potassium_mg": 707 },
      { "item": "Beet Greens (75 g)", "potassium_mg": 655 },
      { "item": "Potato, baked (130 g)", "potassium_mg": 926 },
      { "item": "Pumpkin (75 g)", "potassium_mg": 253 },
      { "item": "Coconut Water (240 mL)", "potassium_mg": 600 },
      { "item": "Plain Yogurt (240 mL)", "potassium_mg": 573 },
      { "item": "White Beans (100 g cooked)", "potassium_mg": 502 },
      { "item": "Clams (85 g cooked)", "potassium_mg": 534 },
      { "item": "Pork Chop (100 g)", "potassium_mg": 540 }
    ]
  },
  "sodium": {
    "low": [
        { "item": "Apple (1 medium, ~180 g)",           "sodium_mg": 1 },
        { "item": "Banana (1 medium, ~120 g)",          "sodium_mg": 1 },
        { "item": "Orange (1 medium, ~180 g)",          "sodium_mg": 0 },
        { "item": "Broccoli (100 g)",                   "sodium_mg": 30 },
        { "item": "Carrot (1 medium, ~60 g)",           "sodium_mg": 50 },
        { "item": "Cucumber (1 cup, ~104 g)",           "sodium_mg": 2 },
        { "item": "Mixed Salad Greens (100 g)",         "sodium_mg": 15 },
        { "item": "Spinach (75 g cooked)",              "sodium_mg": 80 },
        { "item": "Tomato (1 medium, ~120 g)",          "sodium_mg": 6 },
        { "item": "Potato (130 g baked)",               "sodium_mg": 7 },
        { "item": "Brown Rice (100 g cooked)",          "sodium_mg": 5 },
        { "item": "Quinoa (100 g cooked)",              "sodium_mg": 13 },
        { "item": "Egg (1 large, ~50 g)",               "sodium_mg": 70 },
        { "item": "Chicken Breast (100 g)",             "sodium_mg": 60 },
        { "item": "Salmon (100 g)",                     "sodium_mg": 50 },
        { "item": "Sparkling Water (355 mL)",           "sodium_mg": 10 },
        { "item": "Coffee (240 mL)",                    "sodium_mg": 5 }
    ],
    "medium": [
      { "item": "Whole Wheat Bread (1 slice, ~30 g)", "sodium_mg": 130 },
      { "item": "White Bread (1 slice, ~30 g)", "sodium_mg": 140 },
      { "item": "Cheddar Cheese (28 g)", "sodium_mg": 180 },
      { "item": "Cottage Cheese (100 g)", "sodium_mg": 350 },
      { "item": "Canned Beans (100 g drained)", "sodium_mg": 240 },
      { "item": "Peanut Butter (32 g)", "sodium_mg": 150 },
      { "item": "Protein Bar (≈50 g)", "sodium_mg": 200 },
      { "item": "Potato Chips (28 g)", "sodium_mg": 170 },
      { "item": "Hummus (30 g)", "sodium_mg": 80 },
      { "item": "Cola (355 mL)", "sodium_mg": 45 },
      { "item": "Milk (240 mL)", "sodium_mg": 100 },
      { "item": "Chocolate Milk (240 mL)", "sodium_mg": 150 }
    ],
    "high": [
      { "item": "Salt Packet (1 g NaCl)", "sodium_mg": 400 },
      { "item": "Bouillon Cube (1 cube)", "sodium_mg": 900 },
      { "item": "Soy Sauce (15 mL)", "sodium_mg": 920 },
      { "item": "Deli Ham (56 g)", "sodium_mg": 960 },
      { "item": "Pepperoni (28 g)", "sodium_mg": 560 },
      { "item": "Bacon (2 slices, ~30 g)", "sodium_mg": 360 },
      { "item": "Chicken Nuggets (4 pcs, ~75 g)", "sodium_mg": 600 },
      { "item": "Tomato Juice (240 mL)", "sodium_mg": 650 },
      { "item": "Canned Tomato Soup (240 mL)", "sodium_mg": 600 },
      { "item": "Pretzels (28 g)", "sodium_mg": 505 }
    ]
  }
}
